'use strict';
(()=>{
 const $=id=>document.getElementById(id),labels=['أ','ب','ج','د'];let data;
 const text=(tag,value,cls)=>{const el=document.createElement(tag);el.textContent=value;if(cls)el.className=cls;return el;};
 for(const [id,b]of Object.entries(FtmBanks))for(const select of [$('stats-bank'),$('mistakes-bank')])select.add(new Option(b.name,id));
 function duration(seconds){const h=Math.floor(seconds/3600),m=Math.floor(seconds%3600/60),s=seconds%60;return `${h} س ${m} د ${s} ث`;}
 function metrics(){if(!data)return;const s=$('stats-bank').value==='all'?data.total:data.banks[$('stats-bank').value];$('metrics').replaceChildren();for(const [label,value]of [['مدة الاستخدام',duration(s.seconds)],['اختبارات مكتملة',s.tests],['مرات عرض الأسئلة',s.appearances],['أسئلة مختلفة عُرضت',s.shown],['إجابات صحيحة',s.right],['إجابات خاطئة',s.wrong],['أسئلة لم تُعرض',s.unseen],['إجابات متروكة',s.skipped]]){const el=text('div','','account-metric');el.append(text('strong',value),text('span',label));$('metrics').append(el);}}
 function sections(){const id=$('mistakes-bank').value,select=$('mistakes-section');select.replaceChildren(new Option('كل الأقسام','all'));for(const [bank,b]of Object.entries(FtmBanks))if(id==='all'||bank===id)for(const [sec,name]of Object.entries(b.sections))select.add(new Option((id==='all'?b.name+' · ':'')+name,bank+':'+sec));review();}
 function review(){if(!data)return;const root=$('mistakes-list');root.replaceChildren();let count=0;const wanted=$('mistakes-bank').value,section=$('mistakes-section').value;for(const [bank,b]of Object.entries(FtmBanks)){if(wanted!=='all'&&bank!==wanted)continue;const byId=new Map(b.questions.map(q=>[q.id,q]));for(const m of data.banks[bank].mistakes){const q=byId.get(m.id);if(section!=='all'&&section!==bank+':'+q.sec)continue;count++;const card=text('article','','mistake-card');card.append(text('p',`${b.name} · ${b.sections[q.sec]||q.sec} · السؤال ${q.id} · ${m.count} مرة خطأ`),text('h3',q.q));const options=document.createElement('ul');q.opts.forEach((o,i)=>options.append(text('li',`${labels[i]}. ${o}`,i===q.ans?'right':'')));card.append(options,text('p','آخر إجابة خاطئة: '+q.opts[m.answer],'wrong'),text('p','الإجابة الصحيحة: '+q.opts[q.ans],'right'));if(q.notes)card.append(text('p',q.notes,'note'));root.append(card);}}
 $('mistakes-count').textContent=count?`${count} سؤالًا للمراجعة`:'لا توجد أسئلة خاطئة في الاختيار الحالي.';}
 async function load(){const button=$('refresh-stats');button.disabled=true;$('stats-message').textContent='جارٍ تحميل الإحصائيات…';try{await FtmAccount.flush();const r=await fetch('/api/stats');if(!r.ok)throw Error('تعذر تحميل الإحصائيات');data=await r.json();$('last-login').textContent='آخر دخول: '+(data.lastLogin?new Intl.DateTimeFormat('ar-SA',{dateStyle:'medium',timeStyle:'short',timeZone:'Asia/Riyadh',calendar:'gregory'}).format(new Date(data.lastLogin)):'سيُسجّل عند دخولك القادم');$('welcome').textContent='أهلًا '+data.username+'، هنا تقدمكِ المحفوظ في حسابك.';$('stats-message').textContent='';metrics();review();}catch(e){$('stats-message').textContent=e.message;$('stats-message').className='account-error';}finally{button.disabled=false;}}
 $('stats-bank').onchange=metrics;$('mistakes-bank').onchange=sections;$('mistakes-section').onchange=review;$('refresh-stats').onclick=load;sections();load();
})();
